image: python:latest

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache"

cache:
  paths:
    - .cache/pip
    - venv/

before_script:
  - pip install pipenv
  - pipenv run python --version
  - pipenv run pip install cython
  - pipenv install --dev
  - pipenv run pip install -e .

lint:
  stage: test
  script:
  - pipenv run flake8
  allow_failure: true

test:
  script:
  - pipenv run pytest 
  allow_failure: true
 
.run:
  script:
  - python setup.py bdist_wheel
  # an alternative approach is to install and run:
  - pip install dist/*
  # run the command here
  artifacts:
    paths:
    - dist/*.whl

.pages:
  script:
  - pip install sphinx sphinx-rtd-theme
  - cd doc ; make html
  - mv build/html/ ../public/
  artifacts:
    paths:
    - public
  only:
  - master

publish:
  stage: deploy
  before_script:
  - pip install twine 
  script:
  - python setup.py sdist
  - twine upload dist/*
  only:
  - master
  - dev
  when: manual
