image: python:3.6
variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache"

include:
  - local: .gitlab/ci/docs.gitlab-ci.yml
  - local: .gitlab/ci/test.gitlab-ci.yml
  - local: .gitlab/ci/docker.gitlab-ci.yml
  - template: SAST.gitlab-ci.yml

sast:
  variables:
    SAST_EXCLUDED_PATHS: cloud,docker,docs,model,scripts,tests

stages:
  - docs
  - build-base
  - build-meltano
  - test
  - build-runner
  - publish
  - distribute

publish:
  image:
    name: $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG
    entrypoint: [""]
  stage: publish
  before_script:
    - pip install twine
  script:
    - twine upload /meltano/dist/*
  only:
    refs:
      - tags@meltano/meltano
    variables:
      - $CI_COMMIT_TAG =~ /^v*/

digitalocean_marketplace:
  image:
    name: hashicorp/packer
    entrypoint: [""]
  stage: distribute
  script:
    - cd cloud/packer
    - packer build marketplace-image.json
  only:
    refs:
      - tags@meltano/meltano
    variables:
      - $CI_COMMIT_TAG =~ /^v*/

#############
# Publish   #
#############

# registry.gitlab.com/meltano/meltano:<tag> → docker.io/meltano:<tag>
# registry.gitlab.com/meltano/meltano:latest → docker.io/meltano:latest
hub_meltano:
  image: docker:latest
  stage: publish
  services:
    - docker:dind
  variables:
    DOCKERFILE: .
    DOCKER_DRIVER: overlay2
    IMAGE_NAME: meltano/meltano
    IMAGE_TAG: $CI_COMMIT_TAG
    SOURCE_IMAGE: $CI_REGISTRY_IMAGE
  script:
    - docker pull $SOURCE_IMAGE:$IMAGE_TAG
    - docker pull $SOURCE_IMAGE:latest
    - docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_PASSWORD
    - docker tag $SOURCE_IMAGE:$IMAGE_TAG $IMAGE_NAME:$IMAGE_TAG
    - docker tag $SOURCE_IMAGE:latest $IMAGE_NAME:latest
    - docker push $IMAGE_NAME:$IMAGE_TAG
    - docker push $IMAGE_NAME:latest
  only:
    refs:
      - tags
    variables:
      - $CI_COMMIT_TAG =~ /^v*/
