image: python:3.6
variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache"

stages:
    - test
    - publish
    - build

cache:
  paths:
    - .cache/pip
    - venv/

.pipenv_install: &pipenv_install
  - pip install pipenv
  - pipenv run python --version
  - pipenv run pip install cython
  - pipenv install --dev
  - pipenv run pip install -e .

lint:
  stage: test
  before_script: *pipenv_install
  script:
  - pipenv run flake8
  allow_failure: true

test:
  stage: test
  before_script: *pipenv_install
  script:
  - pipenv run pytest 
  allow_failure: true
 
.run:
  script:
  - python setup.py bdist_wheel
  # an alternative approach is to install and run:
  - pip install dist/*
  # run the command here
  artifacts:
    paths:
    - dist/*.whl

.pages:
  script:
  - pip install sphinx sphinx-rtd-theme
  - cd doc ; make html
  - mv build/html/ ../public/
  artifacts:
    paths:
    - public
  only:
  - master

publish:
  stage: publish
  before_script:
  - pip install twine 
  script:
  - python setup.py sdist
  - twine upload dist/*
  only:
  - master
  - dev
  when: manual

dev_build_meltano_cli:
  image: docker:latest
  stage: build
  variables:
    DOCKER_DRIVER: overlay2
  services:
  - docker:dind
  script:
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
  - docker build -t $CI_REGISTRY_IMAGE/meltano-cli:$CI_COMMIT_REF_NAME .
  - docker push $CI_REGISTRY_IMAGE/meltano-cli:$CI_COMMIT_REF_NAME
  except:
  - master

publish_build_meltano_cli:
  image: docker:latest
  stage: build
  variables:
    DOCKER_DRIVER: overlay2
  services:
  - docker:dind
  script:
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
  - docker build -t $CI_REGISTRY_IMAGE/meltano-cli:latest .
  - docker push $CI_REGISTRY_IMAGE/meltano-cli:latest
  only:
  - master
