# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.3.0
  hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: check-yaml
    - id: check-added-large-files
    - id: check-merge-conflict
    - id: check-toml
    - id: debug-statements
- repo: https://github.com/asottile/pyupgrade
  rev: v2.7.4
  hooks:
    - id: pyupgrade
      args:
        - '--py3-plus'
- repo: https://github.com/Yelp/detect-secrets
  rev: v0.14.3
  hooks:
    - id: detect-secrets
      exclude: poetry.lock
# Remove after upgrading to isort >=5
- repo: https://github.com/asottile/seed-isort-config
  rev: v2.2.0
  hooks:
    - id: seed-isort-config
- repo: https://github.com/PyCQA/isort
  rev: 4.3.21-2
  hooks:
    - id: isort
      args:
        - '-sp pyproject.toml'
      additional_dependencies:
        - toml
- repo: https://github.com/psf/black
  rev: 20.8b1
  hooks:
    - id: black
- repo: https://github.com/life4/flakehell
  rev: v.0.7.0
  hooks:
    - id: flakehell
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v0.790
  hooks:
    - id: mypy
- repo: https://github.com/pre-commit/mirrors-eslint
  rev: v7.14.0
  hooks:
    - id: eslint
      additional_dependencies:
        - eslint@5.16.0
        - eslint-plugin-prettier@3.1.0
        - eslint-plugin-vue@5.0.0
