version: '3.1'
services:
  ui:
    image: node:10
    env_file:
    - .env.dev
    working_dir: /meltano/analyze
    volumes:
    - ./src/analyze:/meltano/analyze
    ports:
    - 8080:8080
    command: ['bash', '-c', 'yarn && yarn run dev']
    depends_on:
    - api

  api:
    image: meltano/meltano
    env_file:
      - .env.dev
    working_dir: /meltano
    command: ['meltano', 'ui']
    volumes:
    - ./:/meltano
    ports:
    - 5000:5000

  warehouse_db:
    image: postgres
    environment:
      POSTGRES_DB: warehouse
      POSTGRES_PASSWORD: warehouse
      POSTGRES_USER: warehouse
    ports:
    - '5502:5432'

volumes:
  pgdata:
