settings:
# Project settings
- name: send_anonymous_usage_stats
  kind: boolean
  value: true
  env_aliases: ["!MELTANO_DISABLE_TRACKING"]
- name: project_id

# Environment-specific project settings
- name: database_uri
  value: sqlite:///$MELTANO_PROJECT_ROOT/.meltano/meltano.db

# UI settings
- name: ui.bind_host
  value: "0.0.0.0"
  env_aliases: [MELTANO_API_HOSTNAME]
- name: ui.bind_port
  kind: integer
  value: 5000
  env_aliases: [MELTANO_API_PORT]
- name: ui.workers
  kind: integer
  value: 4
  env_aliases: [WORKERS]
