digitalocean_marketplace:
  image:
    name: hashicorp/packer
    entrypoint: [""]
  stage: distribute
  script:
    - cd cloud/packer
    - packer build marketplace-image.json
  only:
    refs:
      - tags@meltano/meltano
    variables:
      - $CI_COMMIT_TAG =~ /^v*/
